name: sphinx-docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx furo recommonmark
      - name: Sphinx build
        run: |
          sphinx-build llvm _build/llvm
          sphinx-build csapp _build/csapp
          sphinx-build swift-book _build/swift-book
          sphinx-build modern-cxx _build/modern-cxx
          sphinx-build microeconomics _build/microeconomics
          sphinx-build macroeconomics _build/macroeconomics
          sphinx-build INDEX _build
      - name: Custom build
        run: |
          cp .raw/* _build/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true

